### ISSUE TITLE
v2.1 Road Map & Discussion

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#128]
Version 2.1 will be a backward compatible feature release of the 2.x branch.  There will be a slight API _adjustment_ to remove the DatabaseException class; this was done because throwing exceptions was not supported in `__toString()` until PHP 7.4.  For example, if you echo any of the statements or clauses you will receive a fatal error instead of the expected exception.  I have currently replaced the DatabaseException with `trigger_error` @ `E_USER_ERROR`.  Comments on this issue, or any other comments / suggestions are welcome.

[Issues and Changes](https://github.com/FaaPz/PDO/milestone/3)

- [x] `ON DUPLICATE KEY UPDATE` (#86)
- [ ] `CREATE / ALTER TABLE` (#30)
- [ ] Database drivers
  - [x] SqlSrv (#29)
  - [ ] Postgres (#47)
- [x] Multiple insert values per statement (#104 )
